### ISSUE TITLE
feature request: exclude coins with insanely high funding rate

### ISSUE THREAD

**Issue by fahrmairm** [doosjenever/Scripts#2]

**Comment by doosjenever** [comment]
Do you know where we can scavenge this data?

**Comment by Crypto-Joker** [comment]
Alternative or similar request:
ignore licks above lickmaxvalue (10000 for excample)
lickvalue = 2000; lickmaxvalue = 10000

**Comment by doosjenever** [comment]
https://fapi.binance.com/fapi/v1/fundingRate

**Comment by doosjenever** [comment]
Implemented
