### ISSUE TITLE
exclusion of new coins based on coingecko is unreliable 

### ISSUE THREAD

**Issue by fahrmairm** [doosjenever/Scripts#3]
FIL was listed today on binance futures and was on coin gecko already a few hours later while still in a mega pump&dump scheme. It was hence not excluded when setting  $newPairs = $false

**Comment by doosjenever** [comment]
Now using $tradingAge which gets data from https://api.tardis.dev/v1/exchanges/binance-futures, and filters out the availableSince date of Binance Futures
